option('enable_tests', type: 'boolean', value: true,
       description: 'Build tests')

option('test_framework', type: 'combo', choices: ['catch2', 'gtest'], value: 'catch2',
       description: 'Testing framework to use (catch2 or gtest)')

option('enable_python', type: 'boolean', value: false,
       description: 'Build Python bindings (future)')

option('pinocchio_includedir', type: 'string', value: '',
       description: 'Override path to Pinocchio headers, default is /opt/openrobots/include. Needed for native Windows builds.')

option('boost_includedir', type: 'string', value: '',
       description: 'Extra include dir for Pinocchio Boost header dependencies (math, type_traits). Needed for native Windows builds.')
