#include <posetrak/version.hpp>

#include "posetrak_build_version.hpp"  // generated by scripts/gen_version.py

namespace posetrak {

std::string version_string() {
    return std::string(build::GIT_COMMIT) + " built " + build::BUILD_TIMESTAMP;
}

}  // namespace posetrak
